/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burp.customGUI;

import PeachApi.JobWorker;
import PeachApi.PeachApiPreferences;
import burp.IBurpExtenderCallbacks;
import burp.ITab;
import com.peachapisecurity.api.PeachApiSecurity;
import java.awt.Component;

/**
 *
 * @author mike
 */
public class PeachApiTab extends javax.swing.JPanel implements ITab {

    PeachApiPreferences _prefs;
    IBurpExtenderCallbacks _callbacks;
    
    @Override
    public String getTabCaption()
    {
        return "Peach API Security";
    }

    @Override
    public Component getUiComponent()
    {
        // TODO Auto-generated method stub
        return this;
    }

    /**
     * Creates new form PeachApiTab
     */
    public PeachApiTab(PeachApiPreferences prefs, IBurpExtenderCallbacks callbacks)
    {
        _prefs = prefs;
        _prefs.setApiTab(this);
        
        _callbacks = callbacks;
        
        initComponents();
        tabs.add("Settings", new PreferencesEditor(prefs));
    }
    
    public void showTestStatus(JobWorker jobWorker, PeachApiSecurity apiSec)
    {
        if(tabs.getComponentCount() == 2)
        {
            tabs.remove(1);
        }
        
        ScannerResults status = new ScannerResults(_prefs, jobWorker, _callbacks);
        tabs.add("Test Status", status);
        tabs.setSelectedComponent(status);
        
        status.Execute(apiSec);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
