/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burp.customGUI;

import PeachApi.JobWorker;
import PeachApi.PeachApiPreferences;
import PeachApi.StatusUpdateWorker;
import burp.IBurpExtenderCallbacks;
import burp.IHttpRequestResponse;
import burp.IHttpService;
import burp.IScanIssue;
import burp.ITab;
import com.peachapisecurity.api.Fault;
import com.peachapisecurity.api.FaultData;
import com.peachapisecurity.api.Job;
import com.peachapisecurity.api.PeachApiSecurity;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.PrintWriter;
import java.net.URL;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;
import static org.apache.commons.lang.StringEscapeUtils.escapeHtml;

public class ScannerResults extends javax.swing.JPanel
{
    private PeachApiPreferences _prefs;
    private JobWorker _jobWorker;
    private StatusUpdateWorker _testWorker = null;
    private IBurpExtenderCallbacks _callbacks;
    
    public boolean cancelScan = false;

    /**
     * Creates new form ScannerResults
     */
    public ScannerResults(PeachApiPreferences prefs, JobWorker jobWorker, IBurpExtenderCallbacks callbacks)
    {
        _prefs = prefs;
        _jobWorker = jobWorker;
        _callbacks = callbacks;
        initComponents();
        setComponentsActions();
    }
    
    private void setComponentsActions()
    {
        buttonCancel.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent arg0)
            {
                _jobWorker.cancel(false);
                buttonCancel.setEnabled(false);
            }
        });
    }
    
    public void Execute(PeachApiSecurity apiSec)
    {
        _testWorker = new StatusUpdateWorker(apiSec, this, _prefs, _callbacks);
        _testWorker.execute();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testStatusBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelStarted = new javax.swing.JLabel();
        labelFinished = new javax.swing.JLabel();
        labelTestCount = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelIssues = new javax.swing.JLabel();
        labelOperation = new javax.swing.JLabel();

        jLabel1.setText("Status:");

        jLabel2.setText("Started:");

        jLabel3.setText("Finished:");

        labelStatus.setText("   ");

        labelStarted.setText("   ");

        labelFinished.setText("   ");

        labelTestCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTestCount.setText("    ");

        buttonCancel.setText("Cancel Test");

        jLabel5.setText("Issues:");

        labelIssues.setText("    ");

        labelOperation.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStarted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFinished, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(testStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelIssues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCancel)
                            .addComponent(labelTestCount, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelStarted))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelFinished))
                .addGap(19, 19, 19)
                .addComponent(labelOperation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(testStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTestCount)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelIssues))
                .addGap(18, 18, 18)
                .addComponent(buttonCancel)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel labelFinished;
    public javax.swing.JLabel labelIssues;
    public javax.swing.JLabel labelOperation;
    public javax.swing.JLabel labelStarted;
    public javax.swing.JLabel labelStatus;
    public javax.swing.JLabel labelTestCount;
    public javax.swing.JProgressBar testStatusBar;
    // End of variables declaration//GEN-END:variables
}
